### PR TITLE
Use java 8 localdatetime for timestamps

### PR DESCRIPTION
**Pull request by jkoorts**

### CODE REVIEW

**Comment by andre77** [comment]
Hi @jkoorts,

thanks a lot for your contribution, its very appreciated!
one of the core points of this project is actually to be a 1:1 copy of the code provided for the xchange library: https://github.com/timmolter/XChange, see xchange-luno module.
That library still uses [Java 7](https://github.com/timmolter/XChange/blob/develop/pom.xml#L331) for good reasons.

Sure the new Java8 stuf is very cool, i would love to use streams and lambdas where ever i can.
But look, there are applications/projects out there, which must stick with older java version for some reasons. If you include the java8 stuff, those applications/projects can not use the luno library any more.
If you ask me, i would simply convert the Date object to what ever you like in your application code. But its just my own view.

@tstranex what do you think?

**Comment by jkoorts** [comment]
No problem. I'm using that library writing my own  trading platform for
bots to run on. Keen in helping out?

**Comment by dannijax** [comment]
I want to contribute to this project, I would love to help with refactoring to java 8 LocalDatetime for timestamps

**Comment by andre77** [comment]
Hi @dannijax,
thanks a lot for your message, but have you read my post here, where i described the situation with java version 8 and the compatibility issues?

**Pull request closed without merging**
